<?php

$aArticlesMilan = [
    "article-1" => ["title" => "Milano Linate Airport",
        "content" => " (from travelwidget.com) Milano Linate Airport, named after Enrico Forlanini, is the city airport of Milan. The airport is located just outside the city and...",
        "url" => "https://media1-production-mightybell.imgix.net/asset/1440999/LIN_overview_map.png?ixlib=rails-0.3.0&fm=jpg&q=75&auto=format&w=700&h=700&fit=max",
        "source" => "https://globuzzer.mn.co/posts/milano-linate-airport",
        "postedDate" => "Jan 16, 2017",
    ],

    "article-2" => ["title" => "GALLERIA VITTORIO EMANUELE II",
        "content" => "Connecting the Duomo and the Milan Opera house is the magnificent Galleria Vittorio Emanuele II. Today is habited by high end brands stores...",
        "url" => "https://media1-production-mightynetworks.imgix.net/asset/1616082/Galleria-Vittorio-Emanuele-II-5.jpg?ixlib=rails-0.3.0&fm=jpg&q=75&auto=format&w=1400&h=1400&fit=max",
        "source" => "https://globuzzer.mn.co/posts/galleria-vittorio-emanuele-ii",
        "postedDate" => "May 1, 2017",
    ],

    "article-3" => ["title" => "TOP 5 ATTRACTIONS IN MILAN!",
        "content" => "Headed to Milan for a quick getaway and in need of a short list of the best attractions in Milan? Here's my list for the most classical tourist attractions...",
        "url" => "https://media3-production-mightybell.imgix.net/asset/1487285/876MilanoDuomo.JPG?ixlib=rails-0.3.0&fm=jpg&q=75&auto=format&w=1400&h=1400&fit=max",
        "source" => "https://globuzzer.mn.co/posts/top-5-attractions-in-milan",
        "postedDate" => "Apr 16, 2017",
    ],

    "article-4" => ["title" => "Public Transport in Milan",
        "content" => "Milan is the chief town of Lombardia, one of Italy 20 regions, and thus needs to have a supporting metro and bus service. In fact Milan has an extensive...",
        "url" => "https://media3-production-mightybell.imgix.net/asset/1446364/Tram-Milano-Scala-768x512.png?ixlib=rails-0.3.0&fm=jpg&q=75&auto=format&w=700&h=700&fit=max",
        "source" => "https://globuzzer.mn.co/posts/public-transport-in-milan",
        "postedDate" => "Jan 19, 2017",
    ],

    "article-5" => ["title" => "Orio al Serio Airport",
        "content" => "Orio al Serio Airport is located in the municipality of Bergamo and is known for being the Ryanair departure airport.  It is farthest airport of Milan and...",
        "url" => "https://media2-production-mightybell.imgix.net/asset/1441042/BGY_overview_map.png?ixlib=rails-0.3.0&fm=jpg&q=75&auto=format&w=700&h=700&fit=max",
        "source" => "https://globuzzer.mn.co/posts/orio-al-serio-airport",
        "postedDate" => "Jan 17, 2017",
    ],

    "article-6" => ["title" => "Columns of San Lorenzo",
        "content" => "The San Lorenzo Columns are historical roman ruins in the centre of Milan. 16 corinthian columns face a beautiful church, but by night they transform...",
        "url" => "https://media2-production-mightybell.imgix.net/asset/1489948/800px-Colonne_di_san_lorenzo_01.jpg?ixlib=rails-0.3.0&fm=jpg&q=75&auto=format&w=1400&h=1400&fit=max",
        "source" => "https://globuzzer.mn.co/posts/columns-of-san-lorenzo",
        "postedDate" => "Feb 21, 2017",
    ],

    "article-7" => ["title" => "Milan Malpensa Airport",
        "content" => "Milan Malpensa Airport is an international hub 50 minutes by bus from the Milan Centrale Railway Station.  Three different companies go from and to...",
        "url" => "https://media1-production-mightybell.imgix.net/asset/1441034/MilanMalpensa__MXP_.png?ixlib=rails-0.3.0&fm=jpg&q=75&auto=format&w=700&h=700&fit=max",
        "source" => "https://globuzzer.mn.co/posts/milan-malpensa-airport",
        "postedDate" => "Jan 17, 2017",
    ],

    "article-8" => ["title" => "THE DUOMO CATHEDRAL",
        "content" => "HOURS OF ADMISSION: CATHEDRAL Daily 8.00 am - 7.00 pm TERRACES Daily 9.00 am - 7.00 pm CRYPT OF ST. CHARLES (inside the Cathedral) ...",
        "url" => "https://media4-production-mightybell.imgix.net/asset/1527012/6021918222_fa74e4e44d_b.jpg?ixlib=rails-0.3.0&fm=jpg&q=75&auto=format&w=1400&h=1400&fit=max",
        "source" => "https://globuzzer.mn.co/posts/the-duomo-cathedral",
        "postedDate" => "Mar 9, 2017",
    ],

    "article-9" => ["title" => "Italy and fashion: An endless love",
        "content" => "Fall/Winter Show during Milan Fashion Week - the most bizarre catwalk in a fashion history. Photo from Gizmodo From 20th to 26th of February...",
        "url" => "https://media1-production-mightynetworks.imgix.net/asset/2410882/bypfjncsqo61qoa9fuyt.jpg?ixlib=rails-0.3.0&fm=jpg&q=75&auto=format&w=1400&h=1400&fit=max",
        "source" => "https://globuzzer.mn.co/posts/italy-and-fashion-an-endless-love",
        "postedDate" => "Feb 28, 2018",
    ],

    "article-10" => ["title" => "University's student housing",
        "content" => "There are many different reasons why people move to Milan. To come as a student is the best of them in term of the support you are given. For...",
        "url" => "https://media1-production-mightynetworks.imgix.net/asset/1602982/20150930-Einzelzimmer.jpg?ixlib=rails-0.3.0&fm=jpg&q=75&auto=format&w=1400&h=1400&fit=max",
        "source" => "https://globuzzer.mn.co/posts/1096598",
        "postedDate" => "Apr 24, 2017",
    ],
];